### PR TITLE
Fix for #26, 2nd try

### PR DESCRIPTION
**Pull request by guillaumewuip**
I now convert the timezone hour offset correctly in millisecond.

### CODE REVIEW

**Comment by bluejamesbond** [comment]
@guillaumewuip I have pushed into heroku. Take a look

**Comment by guillaumewuip** [comment]
Does it change something for you ?
Dates are printed with +1 hour for me ..

**Comment by bluejamesbond** [comment]
@guillaumewuip Its 1 day off for me.

**Comment by bluejamesbond** [comment]
Shows January 1st but its really January 2nd

**Comment by guillaumewuip** [comment]
Oh ok. I haven't a lot of time these days but I will try to create my heroku debug server to see what going on. It's not easy to dev without that.

**Comment by bluejamesbond** [comment]
Thats fine. Take your time.

**Pull request merged**
